<a href="https://colab.research.google.com/github/Gautham27795/numpy_pandas/blob/main/numpy_102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list1=[1,2,3,4,5]

print(list1)
print(list1[2])

[1, 2, 3, 4, 5]
3


In [3]:
lis=['abc',41,[1,2,3,4,5],list1,True]
lis

['abc', 41, [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], True]

In [4]:
import numpy as np

np.array(lis)

<ipython-input-4-5827b0090380>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(lis)


array(['abc', 41, list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]), True],
      dtype=object)

In [5]:
np1=np.array([0,1,2,3,4,5,6,7,8,9,0])
print(np1)

[0 1 2 3 4 5 6 7 8 9 0]


In [6]:
np1.shape

(11,)

In [7]:
np2=np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np3=np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [9]:
np4=np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#multidimensional
np5=np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np6=np.full((10),6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [12]:
np7=np.full((2,10),6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [13]:
np7[0,0]

6

In [14]:
l=[1,2,3,4,5,6,7,8,9]
l[1:5]

[2, 3, 4, 5]